name: Build Foxogram Desktop

on:
  push:
    branches:
      - workflow

jobs:
  build:
    strategy:
      matrix:
        os: [ macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.0'

      - name: Install Ninja
        uses: turtlesec-no/get-ninja@main

      - name: Build Foxogram
        run: |
          mkdir cmake-build
          cmake -DCMAKE_BUILD_TYPE=Release -DIXWEBSOCKET_INSTALL:BOOL=OFF -DCMAKE_INSTALL_PREFIX=foxogram -G Ninja -B cmake-build
          Ninja -C cmake-build
          cmake --build cmake-build --target install

      - name: Archive Foxogram
        shell: pwsh
        run: |
          if ($env:RUNNER_OS -eq "Windows") {
            7z a ${{ matrix.os }}.zip foxogram
          } else {
            zip -r ${{ matrix.os }}.zip foxogram
          }

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}.zip
          path: ${{ matrix.os }}.zip
