name: Build Desktop

permissions:
  contents: write

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@12aa0336e1e410b3c6dff5e0722547f7a37e8c60 # v4.2.1
        with:
          version: '6.8.0'
          cache: true

      - name: Install Ninja
        uses: turtlesec-no/get-ninja@3e85fb0044ada1440765803dd87c838edf79def8 # main

      - name: Build Foxogram
        shell: pwsh
        run: |
          if ($env:RUNNER_OS -eq "Windows") {
            $env:OPENSSL_ROOT_DIR = "C:/Program Files/OpenSSL/"
          }
          
          make build-${{ github.ref_name == 'main' && 'main' || github.ref_name == 'dev' && 'dev' || 'dev' }}

      - name: Archive Foxogram
        shell: pwsh
        run: |
          if ($env:RUNNER_OS -eq "Windows") {
            7z a foxogram-win.zip foxogram_install
          }
          elseif ($env:RUNNER_OS -eq "macOS") {
            zip -r foxogram-macos.zip foxogram_install/FoxogramDesktop.app
          }
          else {
            zip -r foxogram-linux.zip foxogram_install
          }

      - name: Upload Release
        uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631 # v2.2.2
        with:
          name: Foxogram ${{ github.run_id }}
          tag_name: foxogram-${{ github.run_id }}
          files: "foxogram-*.zip"
