name: Build Foxogram Desktop

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.0'

      - name: Build Foxogram
        run: |
          mkdir cmake-build
          tree
          cmake -DCMAKE_BUILD_TYPE=Release -DIXWEBSOCKET_INSTALL:BOOL=OFF -DCMAKE_INSTALL_PREFIX=foxogram -B cmake-build
          cmake --build cmake-build --target install

      - name: Archive Foxogram
        shell: pwsh
        run: |
          if ($env:RUNNER_OS -eq "Windows") {
            7z a foxogram-desktop-${{ matrix.os }}.zip foxogram
          } else {
            zip -r foxogram-desktop-${{ matrix.os }}.zip foxogram
          }

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: foxogram-desktop-${{ matrix.os }}.zip

  upload:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            foxogram-desktop-ubuntu-latest.zip
            foxogram-desktop-macos-latest.zip
            foxogram-desktop-windows-latest.zip
