name: Build Desktop

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.0'

      - name: Install Ninja
        if: runner.os != 'Windows'
        uses: turtlesec-no/get-ninja@main

      - name: Build Foxogram
        shell: pwsh
        run: |
          make

      - name: Archive Foxogram
        shell: pwsh
        run: |
          if ($env:RUNNER_OS -eq "Windows") {
            7z a foxogram-win.zip foxogram
          }
          elseif ($env:RUNNER_OS -eq "macOS") {
            zip -r foxogram-macos.zip foxogram/foxogram.app
          }
          else {
            zip -r foxogram-linux.zip foxogram
          }

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          name: Foxogram ${{ github.run_id }}
          tag_name: foxogram-${{ github.run_id }}
          files: "foxogram-*.zip"
